# Generated by Django 3.0.7 on 2020-06-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileSystem',
        ),
    ]
